# Generated by Django 4.2.1 on 2023-05-14 14:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "nom",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(default="", max_length=500)),
                (
                    "prix",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9999),
                        ],
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="image_service/default.png", upload_to="image_service"
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
        migrations.CreateModel(
            name="Devis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Last_name",
                    models.CharField(
                        default="", help_text="Nom de famille", max_length=50
                    ),
                ),
                (
                    "First_name",
                    models.CharField(default="", help_text="Prénom", max_length=50),
                ),
                (
                    "adresse",
                    models.CharField(help_text="1 rue des abricotiers", max_length=200),
                ),
                ("ville", models.CharField(help_text="Paris", max_length=50)),
                (
                    "code_postal",
                    models.CharField(
                        help_text="Entrez un code postal valide",
                        max_length=5,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le code postal doit contenir 5 chiffres",
                                regex="^[0-9]{5}$",
                            )
                        ],
                        verbose_name="Code postal",
                    ),
                ),
                ("pays", models.CharField(help_text="France", max_length=50)),
                ("tel",
                    models.CharField(
                        default="",
                        help_text="Numéro de téléphone",
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{10}$",
                                "Le numéro de téléphone doit comporter 10 chiffres.",
                            )
                        ],
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Devis",
                "verbose_name_plural": "Devis",
            },
        ),
    ]
