# Generated by Django 4.2.1 on 2023-05-07 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_alter_service_prix"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Devi",
            new_name="Devis",
        ),
    ]
