# Generated by Django 4.2.1 on 2023-05-07 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_rename_devi_devis"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="devis",
            options={"verbose_name": "Devis", "verbose_name_plural": "Devis"},
        ),
        migrations.AlterModelOptions(
            name="service",
            options={"verbose_name": "Service", "verbose_name_plural": "Services"},
        ),
    ]
