"""
Django settings for econet project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
#from dotenv import load_dotenv
#from .encryption import decrypt
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-j-&hsj)41ctdtw=u&58kanh3nj&j4lt3e@pq_v_2!xnwt*vh3t"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin', #outils pour modifier l'esthetique de l'interface admin django de notre site
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "listings"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "econet.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "econet.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

JAZZMIN_UI_TWEAKS = {
    # Définit si le texte de la barre de navigation doit être petit.
    "navbar_small_text": False,

    # Définit si le texte du pied de page doit être petit.
    "footer_small_text": False,

    # Définit si le texte du corps doit être petit.
    "body_small_text": False,

    # Définit si le texte du nom de la marque doit être petit.
    "brand_small_text": False,

    # Change la couleur de la marque en rouge.
    "brand_colour": "#FF0000",

    # Change la couleur de la barre de navigation en rouge foncé.
    "navbar": "navbar-dark bg-danger",

    # Définit si la bordure de la barre de navigation doit être supprimée.
    "no_navbar_border": False,

    # Définit si la barre de navigation doit être fixée en haut de la page.
    "navbar_fixed": True,

    # Définit si la barre latérale doit être fixée en place.
    "sidebar_fixed": True,

    # Définit le style de la barre latérale.
    #"sidebar": "sidebar-dark-primary",
    "sidebar": "sidebar-dark-info", #la couleur est bleu cyan elle s'active lorsqu'on est sur l'onglet sélectionner
    # Définit si le texte de la barre latérale doit être petit.
    "sidebar_nav_small_text": False,

    # Définit si la barre latérale peut être développée ou non.
    "sidebar_disable_expand": False,

    # Définit l'indentation pour les éléments de navigation de niveau enfant dans la barre latérale.
    "sidebar_nav_child_indent": True,

    # Définit si la barre latérale doit avoir un style compact.
    "sidebar_nav_compact_style": True,

    # Définit le nom de l'application.
    #"app_name": "Nom de l'application",

    # Définit si l'option de construction d'interface utilisateur doit être affichée ou non.
    "show_ui_builder": False,
}

# Définir la clé API Sendinblue
SENDINBLUE_API_KEY = os.environ.get('SENDINBLUE_API_KEY')